name: CI/CD Java BE

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Test
        run: mvn clean install
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Connect to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${EC2_KEY}" > ec2_key.pem
          chmod 400 ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            echo 'Connected to EC2'
            if [ ! -d ~/app ]; then
              git clone git@github.com:tungcbh/nrc-hackathon-be.git ~/app
            fi
            cd ~/app/nrc-hackathon-be
            git fetch origin
            git checkout release
            git reset --hard origin/release
            mvn clean install -DskipTests
            sudo systemctl stop nrc-hackathon-be
            sudo systemctl start nrc-hackathon-be
          EOF
